---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: staging
data:
  NEW_FEATURE: "false"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: frontend-primary
  namespace: staging
  labels:
    stack: frontend
    tier: staging
    canary: "false"
    app: simple-service
spec:
  replicas: 2
  selector:
    matchLabels:
      stack: frontend
      tier: staging
      canary: "false"
  template:
    metadata:
      labels:
        stack: frontend
        tier: staging
        canary: "false"
    spec:
      containers:
      - name: primary
        image: berghl/simple-frontend:0.0.1
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
        envFrom:
        - configMapRef:
            name: frontend-config
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: staging
spec:
  selector:
    stack: frontend
    tier: staging
    app: simple-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend-primary
  namespace: staging
  labels:
    stack: backend
    tier: staging
    canary: "false"
    app: simple-service
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: backend
      tier: staging
      canary: "false"
  template:
    metadata:
      labels:
        stack: backend
        tier: staging
        canary: "false"
    spec:
      containers:
      - name: primary
        image: berghl/simple-backend:0.0.1
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: staging
spec:
  selector:
    stack: backend
    tier: staging
    app: simple-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
